### ISSUE TITLE
Verlinkte Seite der Linksammlung nicht mehr vorhanden

### ISSUE THREAD

**Issue by dkathmann** [th-koeln/mi-bachelor-wba1#10]
Ich wollte nur kurz anmerken, dass die bei der Linksammlung verlinkte Seite [webdesignerschecklist.com](http://webdesignerschecklist.com/) nicht mehr vorhanden ist.

[Link zum GitHub-Element](https://github.com/th-koeln/mi-bachelor-wba1/blob/master/_links/webdesignchecklist.md)

**Comment by cnoss** [comment]
danke!

**Comment by dkathmann** [comment]
@cnoss vielleicht ist das hier eine interessante Alternative: [Front-End-Checklist](https://github.com/thedaviddias/Front-End-Checklist)
