### ISSUE TITLE
Freischaltung der Terminanmeldung

### ISSUE THREAD

**Issue by dkathmann** [th-koeln/mi-bachelor-wba1#11]
Wann werden die kommenden Termine zur Anmeldung freigeschaltet und auf welchem Kanal wird dies kommuniziert (E-Mail, wieder hier über GitHub, oder gar nicht)?

**Comment by vschaefer** [comment]
Hi, die Termine für nächsten und übernächsten Donnerstag sind spätestens morgen früh online. Ich werde dazu hier ein Issue erstellen.
