### ISSUE TITLE
Github-Repository

### ISSUE THREAD

**Issue by kdueckma** [th-koeln/mi-bachelor-wba1#43]
Wir hätten die Möglichkeit, ein privates Repository zu erstellen und alle Betreuer als Contributer hinzuzufügen. Sollen wir das machen, oder ist es besser und einfacher, ein öffentliches Repository zu benutzen?

**Comment by cnoss** [comment]
Ich fände es eigentlich hübscher, wenn die Repos offen wären … die GitHub.io Seite ist stets automatisch offen. Müssen Sie für sich entscheiden.
