### ISSUE TITLE
Responsive Probleme

### ISSUE THREAD

**Issue by CharaSensei** [th-koeln/mi-bachelor-wba1#44]
Ich habe für die Challenge am Donnerstag eine Seite mit einem Überblick über Javascript Grundlagen für meine Gruppe erstellt und habe an dieser Seite noch ein paar Funktionen vom Responsive-Design geübt. Wenn ich die Dateien von meinem Laptop aus öffne funktioniert alles wie gewollt und ändert sich auch, wenn ich die Fensterbreite ändere so wie es geplant ist.
Ich habe dann versucht das ganze in meinem adv Verzeichnis hochzuladen damit es online ist mit htaccess und Passwort für die Challenge. Wenn ich das dann öffne mit dem Link (http://www.gm.fh-koeln.de/~inf181/  Zugang: wba1/wba1), lädt er die richtige Seite, aber es verändert sich nichts mehr beim ändern der Fensterbreite. Alle responsive Funktionen funktionieren nur, wenn ich es als lokale Datei öffne, aber nicht mehr über die adv Seite.

Haben Sie eine Idee woran das liegt?
Die Responsive Funktion habe ich mit @media in css umgesetzt.

Lokal
<img width="603" alt="lokal" src="https://user-images.githubusercontent.com/32841987/33600910-f2fd48cc-d9aa-11e7-8f3c-228fb09ba14b.png">

Online
<img width="600" alt="online" src="https://user-images.githubusercontent.com/32841987/33600911-f31f8df6-d9aa-11e7-944b-288039a487d4.png">

**Comment by slemke** [comment]
Hi,

bei mir sieht es auf wie auf dem Bild der lokalen Version. Hast du bereits die üblichen Verdächtigen wie Cache ausgeschlossen?

**Comment by CharaSensei** [comment]
Okay danke, das hat geholfen.
Hatte gedacht, dass das es das nicht ist, weil die Seite in nem anderem Browser auch nicht ging, aber wenn ich den Cache leere geht es jetzt in beiden. War wohl im anderen auch schon "kaputt".
