### ISSUE TITLE
Termin "Beratung studentische Workshops"

### ISSUE THREAD

**Issue by JulianSchoem** [th-koeln/mi-bachelor-wba1#9]
Hallo,

meine Frage wäre, worum es sich bei diesem Termin "Beratung studentische Workshops" handelt? Gibt es die Möglichkeit als Student selber Workshops zu leiten?

Danke im Voraus für die Antwort.

Viele Grüße,
Julian Schoemaker

**Comment by cnoss** [comment]
Genau. Dazu werd ich Dotag noch mal was erzählen. Das richtet sich an Studierende mit entsprechenden WebDev Skills. Könnte bei Ihnen doch passen, oder? Sollte ein Zweierteam sein.

**Comment by JulianSchoem** [comment]
Das könnte passen und hört sich interessant an! Dann bin ich gespannt auf Donnerstag.
